//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design_Dashboard_Modern
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detail
    {
        public int order_detail_id { get; set; }
        public Nullable<int> Order_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Pro_id { get; set; }
        public string order_note { get; set; }
        public Nullable<double> order_total_price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
