//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design_Dashboard_Modern
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_detail = new HashSet<Order_detail>();
        }
    
        public int Pro_id { get; set; }
        public string Pro_name { get; set; }
        public string Pro_detail { get; set; }
        public Nullable<bool> Pro_status { get; set; }
        public Nullable<int> Cate_id { get; set; }
        public Nullable<double> Pro_Price { get; set; }
        public Nullable<int> Provider_id { get; set; }
        public Nullable<int> Pro_quantity { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Receipt_Detail Receipt_Detail { get; set; }
    }
}
