//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design_Dashboard_Modern
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Detail
    {
        public Nullable<int> Receipt_id { get; set; }
        public int Pro_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Pro_Price { get; set; }
        public Nullable<double> Sum_Price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
